version: '3.3'

services:

  # Use HiveMQ or Mosquitto

  hivemq:
    container_name: hivemq
    hostname: hivemq
    image: hivemq/hivemq4
    ports:
      - 1883:1883
      - 33080:8080 # admin user/pass: admin/hivemq

  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  # MQTT to Kafka
  simple-kafka-mqtt-connector:
    image: arthurgrigo/simple-kafka-mqtt-connector:0.0.1-SNAPSHOT
    restart: always
    hostname: simple-kafka-mqtt-connector
    container_name: simple-kafka-mqtt-connector
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_CLIENT_ID: simple-kafka-mqtt-connector-1
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: simple-kafka-mqtt-connector-1
      MQTT_QOS: 2
      TOPIC_MAPPING: MqttTopic>>>KafkaTopic;
