version: "3.1"

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_volume:/var/lib/mysql

  # http://localhost:3307/
  # username / pass: root / root
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '3307:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mariadb
    depends_on:
      - mariadb

volumes:
  mariadb_volume: